name: Build and release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Get tag
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: ${{ steps.get_tag.outputs.tag }}
          body: |
            Release ${{ steps.get_tag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Windows version
        uses: docker/build-push-action@v5
        with:
          context: ./windows
          platforms: linux/amd64
          push: true
          tags: ghcr.io/r-dvl/golang-builder:windows
          labels: Windows Golang builder

      - name: Build and push Linux version
        uses: docker/build-push-action@v5
        with:
          context: ./linux
          platforms: linux/amd64
          push: true
          tags: ghcr.io/r-dvl/golang-builder:linux
          labels: Linux Golang builder

      - name: Build and push Linux version
        uses: docker/build-push-action@v5
        with:
          context: ./darwin
          platforms: linux/amd64
          push: true
          tags: ghcr.io/r-dvl/golang-builder:darwin
          labels: Darwin Golang builder