name: Publish Docker image

on:
    push:
      tags:
        - '*'

jobs:
  push_to_registries:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - name: Build and push Linux image
        uses: docker/build-push-action@v4
        with:
          context: ./linux
          platforms: linux/amd64
          push: true
          tags: linux
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Windows image
        uses: docker/build-push-action@v4
        with:
          context: ./windows
          platforms: windows/amd64
          push: true
          tags: windows
          labels: ${{ steps.meta.outputs.labels }}