name: Build and publish

on:
  release:
    types: [published]

jobs:
  push_to_registries:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Linux image
        uses: docker/build-push-action@v4
        with:
          context: ./linux
          platforms: linux/amd64
          push: true
          tags: linux
          labels: Linux Golang Builder

      - name: Build and push Windows image
        uses: docker/build-push-action@v4
        with:
          context: ./windows
          platforms: windows/amd64
          push: true
          tags: windows
          labels: Windows Golang Builder